### ISSUE TITLE
Build gets stuck on first step (Ubuntu 22)

### ISSUE THREAD

**Issue by MoritzVolkman** [bcgov/von-agent-template#68]
Hey Everyone,

I have encountered some problems while trying to build von-agent-template.
On Ubuntu 22.04, when I am using the command ./manage build, I get the following error message:

*ERROR: Service 'myorg-agent' failed to build: manifest for bcgovimages/von-image:py36-1.7-ew-0 not found: manifest unknown: manifest unknown*

During build step 1/16.

Do you have any ideas for a work around or fix for that?

Thanks a lot in advance

**Comment by esune** [comment]
The project has reached eol and the repository is being archived.

For what is worth, that image is not available in Docker Hub, you could try using a different image such as `bcgovimages/von-image:py36-1.16-1` however I am not sure on the results as it has been a long time since this project was last built/maintained/used.
